name: awesome_todo_app
description: A basic todo app using Riverpod and Local Storage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  uuid: ^3.0.6
  http: ^0.13.5
  drift: ^2.22.1
  drift_flutter: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  riverpod_generator: ^2.3.11
  drift_dev: ^2.22.0
  build_runner: ^2.4.13

flutter:

  uses-material-design: true
